### ISSUE TITLE
corax:property should be sumo-cora:property

### ISSUE THREAD

**Issue by fiveop** [srfiorini/IEEE1872-owl#2]
The object property 'property' should be in sumo-cora, not corax.

See https://github.com/srfiorini/IEEE1872-owl/blob/60a09f3850c198d7ae125e670783208d471d350c/corax.owl#L180

**Comment by srfiorini** [comment]
It should be fixed now, @fiveop . Please, take a look at branch `fix-sumo-property`. Are they ok for what you are using the ontology for? If so, I will merge this in the `master`.

Thanks for the issue report, btw.

**Comment by fiveop** [comment]
Looks good. Thank you.
